### ISSUE TITLE
 Unable to access the nextcloud home page

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-nextcloud#12]
nextcloud 22 访问不了80主页面
#### nginx 80端口正常
![image](https://user-images.githubusercontent.com/86603933/139784532-aa1d0848-2a2c-46c9-a2e0-0c4baecdac94.png)

### Bug Screenshot

![image](https://user-images.githubusercontent.com/86603933/139783972-a736fc9e-aa19-4950-b8fd-c0295bb7d601.png)

**Comment by qiaofeng1227** [comment]
nextcloud test on apache, nginx not support
