### ISSUE TITLE
Nextcloud 20.0.5:   Missing nextcloud version information, please add information

### ISSUE THREAD

**Issue by hnczhjh** [Websoft9/ansible-nextcloud#6]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [x] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
        "httpd  Server version: Apache/2.4.46 (IUS)", 
        "mysql  Ver 14.14 Distrib 5.7.34, for Linux (x86_64) using  EditLine wrapper", 
        "PHP 7.4.21 (cli) (built: Jun 29 2021 15:17:15) ( NTS )", 
        "Docker version 20.10.7, build f0df350", 
        "phpmyadmin version: \"version\": \"5.1.1\",", 
        "onlyofficedocs version: 6.3.1-32", 
        "Redis server v=5.0.9 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=ea3fdd6930dedd65", 
        "System version: Amazon 2", 
        "Image name: nextcloud20.0.5-AmazonLinux2"
```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/86603933/124690949-973f2980-df0d-11eb-8ee3-69fcbe1ae279.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
Have to repair:

![image](https://user-images.githubusercontent.com/63622990/124857004-1ac84b80-dfde-11eb-8387-a7a812feace7.png)
