### ISSUE TITLE
skip wizard installation

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-nextcloud#7]
1. skip wizard installation, complete install
2. slove these warnings
![image](https://user-images.githubusercontent.com/43192516/125926311-7cc9cabb-8d53-4a57-a14a-5456507b03b4.png)

**Comment by zengxc-1996** [comment]
set phone region:
config.php add this line,
`'default_phone_region' => 'CN',`
CN default is china.

**Comment by zengxc-1996** [comment]
![image](https://user-images.githubusercontent.com/63622990/126110716-cdfb28f1-64ec-4301-b5d3-437068159b73.png)

**Comment by zengxc-1996** [comment]
```
[root@iZj6cajh1kiifvbr189ybhZ ~]# cat /var/log/httpd/nextcloud-error_log 

[Mon Jul 19 14:56:03.452431 2021] [access_compat:error] [pid 15958:tid 15958] [client 47.242.205.54:42282] AH01797: client denied by server configuration: /data/wwwroot/nextcloud/data/.ocdata
[Mon Jul 19 15:02:10.675777 2021] [access_compat:error] [pid 17106:tid 17106] [client 47.242.205.54:42502] AH01797: client denied by server configuration: /data/wwwroot/nextcloud/data/.ocdata
```
